lag_admin:
    resource: .
    prefix: /
    type: extra

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

# Guard
login:
    path: /login
    defaults: {_controller: AppBundle:Guard:login}

login_check:
    path: /login_check
    defaults: {_controller: AppBundle:Guard:loginCheck}

logout:
    path: /logout
