security:
    encoders:
        AppBundle\Entity\George: sha512

    providers:
        lag_provider:
            id: lag_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            logout:
                path: /logout
                target: /login

            guard:
                authenticators:
                    - lag.guard.password_authenticator

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
