parameters:

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [setAnnotationReader, ['@annotation_reader']]

    lag.guard.password_authenticator:
       class: AppBundle\Guard\Authenticator\PasswordAuthenticator
       arguments:
           - '@router'
           - '@form.factory'
           - '@security.encoder_factory'

    lag_user_provider:
       class: AppBundle\Guard\UserProvider\UserProvider
       arguments:
       - '@lag.george_repository'
       - '@validator'

    lag.project_repository:
        class: AppBundle\Repository\ProjectRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Project

    lag.worked_day_repository:
        class: AppBundle\Repository\WorkedDaysRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\WorkedDay

    lag.customer_repository:
        class: AppBundle\Repository\CustomerRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Customer

    lag.george_repository:
        class: AppBundle\Repository\GeorgeRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\George

    lag.george_profile_repository:
        class: AppBundle\Repository\GeorgeProfileRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\GeorgeProfile

    lag.reporting.view_helper:
        class: AppBundle\View\Helper\ReportingHelper
        arguments:
            - '@lag.project_repository'
            - '@lag.worked_day_repository'
            - '@router'
            - '@security.token_storage'
