parameters:

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    lag.project_repository:
        class: AppBundle\Repository\ProjectRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Project

    lag.worked_day_repository:
        class: AppBundle\Repository\WorkedDaysRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\WorkedDay

    lag.customer_repository:
        class: AppBundle\Repository\CustomerRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Customer

    lag.george_repository:
        class: AppBundle\Repository\GeorgeRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\George

    lag.george_profile_repository:
        class: AppBundle\Repository\GeorgeProfileRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\GeorgeProfile

    lag.reporting.view_helper:
        class: AppBundle\View\Helper\ReportingHelper
        arguments:
            - '@lag.project_repository'
            - '@lag.worked_day_repository'
