---
- hosts: all
  become: yes

  vars:
    ansible_user: johnkrovitch

  tasks:
    ###################
    # User Management
    ###################
    - name: Create {{ user }} user group
      group:
        name={{ user }}

    - name: Create user {{ user }}
      user:
        name={{ user }}
        comment="{{ user }} user"
        shell=/bin/zsh
        groups={{ user }},ssh,www-data

    - name: Add my public key to {{ user }}
      authorized_key:
        user={{ user }}
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    ###################
    # Database
    ###################
    - name: Create database {{ database_name }}
      mysql_db:
        name={{ database_name }}
        state=present
        login_user=root
        login_password={{ database_root_password }}

    - name: Create user {{ database_user }} for database {{ database_name }}
      mysql_user:
        name={{ database_user }}
        password={{ database_password }}
        priv={{ database_name }}.*:ALL
        state=present
        login_user=root
        login_password={{ database_root_password }}

    ###################
    # Website
    ###################
    - name: Create www directory in {{ user }} home
      file:
        path=/home/{{ user }}/www
        state=directory
        mode=0755
        owner={{ user }}
        group={{ user }}

    - name: Create vhost
      template:
        src=../templates/virtualhost.j2
        dest=/etc/apache2/sites-available/{{ server_name }}.conf
        force=yes
      notify:
      - restart apache

    - name: Enable {{ server_name }} site
      command: a2ensite {{ server_name }}.conf

    - name: Add ssh key to know hosts
      known_hosts: path='/home/{{ user }}/.ssh/known_hosts'
                   name='github.com'
                   key="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

  ###################
  # Handlers
  ###################
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted enabled=yes

